# Generated by Django 5.0.6 on 2024-06-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('description', models.TextField(default='')),
                ('phone', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
