# Generated by Django 5.0.6 on 2024-07-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
