# Generated by Django 5.0.6 on 2024-07-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='city',
        ),
    ]
