# Generated by Django 5.0.6 on 2024-07-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_orders_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
