# Generated by Django 5.0.6 on 2024-07-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_orders_items_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestap', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
